apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: sample-applicationset
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: https://github.com/michaelochristensen/applicationset-demo
        revision: HEAD
        files:
          - path: manifests/apps.yaml
  template:
    metadata:
      name: '{{name}}'
    spec:
      project: default
      source:
        repoURL: https://github.com/michaelochristensen/applicationset-demo
        targetRevision: HEAD
        path: '{{path}}'
      destination:
        server: '{{server}}'
        namespace: '{{namespace}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
